name: Organization Ci

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Olá, mundo!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.