
name: CI


on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3


      - name: Install dependencies
        run: npm install

      - name: Install Commitlint
        run: npm install @commitlint/{config-conventional,cli}

      - name: Validate Commit Messages
        run: npx commitlint --from HEAD~1

