
name: CI


on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3


      - name: Install backend dependencies
        working-directory: A3-Gestao\neskschool\src\back-end
        run: npm install

      - name: Run backend
        working-directory: A3-Gestao\neskschool\src\back-end
        run: npm run dev

      - name: Install frontend dependencies
        working-directory: A3-Gestao\neskschool\src\front-end
        run: npm install

      - name: Run frontend
        working-directory: A3-Gestao\neskschool\src\front-end
        run: npm run start



